import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';
import { defaultStoreSettings } from '../finance/financeUtils';

type Settings = { companyName: string; phone: string; whatsapp: string; address: string; whatsappMessage: string; privacyMessage: string };
const initial: Settings = defaultStoreSettings;

export function SettingsPage() { const [form, setForm] = useState<Settings>(initial); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  useEffect(() => { if (!supabase) { setLoading(false); return; } supabase.from('store_settings').select('key,value').in('key', ['store_profile', 'whatsapp_messages', 'privacy']).then(({ data, error: queryError }) => { if (queryError) setError('Não foi possível carregar as configurações.'); const values: any = Object.fromEntries((data || []).map(item => [item.key, item.value])); const merged = { ...initial, ...(values.store_profile || {}), ...(values.whatsapp_messages || {}), ...(values.privacy || {}) }; setForm(Object.fromEntries(Object.entries(initial).map(([key, fallback]) => [key, merged[key] || fallback])) as Settings); setLoading(false); }); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); if (!supabase) return; setSaving(true); setError(''); const payloads = [{ key: 'store_profile', value: { companyName: form.companyName, phone: form.phone, whatsapp: form.whatsapp, address: form.address } }, { key: 'whatsapp_messages', value: { whatsappMessage: form.whatsappMessage } }, { key: 'privacy', value: { privacyMessage: form.privacyMessage } }]; const result = await supabase.from('store_settings').upsert(payloads, { onConflict: 'key' }); if (result.error) setError('Não foi possível salvar as configurações.'); else setSuccess('Configurações salvas com sucesso.'); setSaving(false); }
  if (loading) return <section className="content"><div className="empty">Carregando configurações…</div></section>;
  return <section className="content"><div className="page-heading"><div><div className="eyebrow">Sistema</div><h2>Configurações</h2><p>Dados da loja, mensagens automáticas e privacidade.</p></div></div>{success && <div className="success" role="status">{success}</div>}<form className="form-card" onSubmit={submit}><h3>Dados da loja</h3><div className="form-grid"><div className="field"><label htmlFor="settings-company">Nome da empresa <span className="required">*</span></label><input id="settings-company" className="input" value={form.companyName} onChange={e => setForm({ ...form, companyName: e.target.value })} required /></div><div className="field"><label htmlFor="settings-phone">Telefone</label><input id="settings-phone" className="input" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></div><div className="field"><label htmlFor="settings-whatsapp">WhatsApp</label><input id="settings-whatsapp" className="input" value={form.whatsapp} onChange={e => setForm({ ...form, whatsapp: e.target.value })} /></div><div className="field"><label htmlFor="settings-address">Endereço</label><input id="settings-address" className="input" value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} /></div><div className="field full"><label htmlFor="settings-message">Mensagem automática do WhatsApp</label><textarea id="settings-message" className="textarea" value={form.whatsappMessage} onChange={e => setForm({ ...form, whatsappMessage: e.target.value })} /></div><div className="field full"><label htmlFor="settings-privacy">Preferências de privacidade/LGPD</label><textarea id="settings-privacy" className="textarea" value={form.privacyMessage} onChange={e => setForm({ ...form, privacyMessage: e.target.value })} /></div></div>{error && <div className="error" role="alert">{error}</div>}<div className="actions"><button className="btn primary" disabled={saving}>{saving ? 'Salvando…' : 'Salvar configurações'}</button></div></form></section>; }
