import { FormEvent, useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Icon } from '../ui/Icon';
import { supabase } from '../../lib/supabase';

type Result = { id: string; label: string; detail: string; category: string; to: string };
const statusLabels: Record<string, string> = { received: 'Recebido', diagnosis: 'Em diagnóstico', repair: 'Em reparo', ready: 'Pronto para retirada', delivered: 'Entregue', cancelled: 'Cancelado', awaiting_approval: 'Aguardando aprovação' };

export function GlobalSearch() {
  const [term, setTerm] = useState(''); const [results, setResults] = useState<Result[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const requestRef = useRef(0); const navigate = useNavigate();
  useEffect(() => { const query = term.trim(); const client = supabase; const requestId = ++requestRef.current; if (query.length < 2 || !client) { setResults([]); setLoading(false); setError(''); return; } const safeQuery = query.replace(/[,%()]/g, ' '); const timer = window.setTimeout(async () => { setLoading(true); setError(''); const [customers, orders, devices, products, sales] = await Promise.all([client.from('customers').select('id,full_name,phone').or(`full_name.ilike.%${safeQuery}%,phone.ilike.%${safeQuery}%`).is('archived_at', null).limit(5), client.from('work_orders').select('id,number,status,public_code').or(`number.eq.${Number(query) || 0},public_code.ilike.%${safeQuery}%`).is('archived_at', null).limit(5), client.from('devices').select('id,brand,model').or(`brand.ilike.%${safeQuery}%,model.ilike.%${safeQuery}%`).is('archived_at', null).limit(5), client.from('products').select('id,name,brand').or(`name.ilike.%${safeQuery}%,brand.ilike.%${safeQuery}%`).is('archived_at', null).limit(5), client.from('sales').select('id,total,created_at').ilike('id', `%${safeQuery}%`).limit(5)]); if (requestId !== requestRef.current) return; const failed = [customers, orders, devices, products, sales].find(item => item.error); if (failed?.error) { setError('Não foi possível realizar a busca.'); setResults([]); setLoading(false); setOpen(true); return; } const next: Result[] = [...(customers.data || []).map(row => ({ id: row.id, label: row.full_name, detail: row.phone, category: 'Cliente', to: `/admin/clientes/${row.id}` })), ...(orders.data || []).map(row => ({ id: row.id, label: `Comanda #${row.number}`, detail: statusLabels[row.status] || 'Comanda', category: 'Comanda', to: `/admin/comandas/${row.id}` })), ...(devices.data || []).map(row => ({ id: row.id, label: `${row.brand} ${row.model}`, detail: 'Aparelho', category: 'Aparelho', to: '/admin/aparelhos' })), ...(products.data || []).map(row => ({ id: row.id, label: row.name, detail: row.brand || 'Produto', category: 'Produto', to: '/admin/produtos' })), ...(sales.data || []).map(row => ({ id: row.id, label: `Venda ${row.id.slice(0, 8)}`, detail: `R$ ${Number(row.total || 0).toFixed(2).replace('.', ',')}`, category: 'Venda', to: '/admin/vendas' }))]; setResults(next); setLoading(false); setOpen(true); }, 250); return () => window.clearTimeout(timer); }, [term]);
  function clear() { setTerm(''); setResults([]); setError(''); setOpen(false); }
  function submit(event: FormEvent) { event.preventDefault(); if (results[0]) { navigate(results[0].to); clear(); } }
  return <div className="search-shell"><form className="global-search" onSubmit={submit} role="search"><Icon name="search" size={17} /><input aria-label="Busca global" placeholder="Buscar cliente, comanda..." value={term} onChange={event => { setTerm(event.target.value); setOpen(true); }} onFocus={() => term.length >= 2 && setOpen(true)} />{term && <button type="button" className="search-clear" aria-label="Limpar busca" onClick={clear}>×</button>}</form>{open && term.trim().length >= 2 && <div className="search-results" role="listbox" aria-label="Resultados da busca">{loading ? <div className="search-feedback" role="status">Buscando…</div> : error ? <div className="search-feedback error" role="alert">{error}</div> : results.length ? results.map(result => <button type="button" role="option" key={`${result.category}-${result.id}`} onClick={() => { navigate(result.to); clear(); }}><span><strong>{result.label}</strong><small>{result.detail}</small></span><em>{result.category}</em></button>) : <div className="search-feedback">Nenhum resultado encontrado</div>}</div>}</div>;
}
