import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabase';
import { EmptyState } from '../../components/ui/EmptyState';
import { useToast } from '../../components/ui/ToastProvider';
import { Pagination, usePagination } from '../../components/ui/Pagination';

type Category = { id: string; name: string };
type Product = { id: string; name: string; brand: string | null; condition: string; sale_price: number; cost_price: number; quantity: number; minimum_stock: number; active: boolean; category_id: string | null; categories?: { name: string } | { name: string }[] | null };
type MovementType = 'entry' | 'exit' | 'adjustment';

const movementLabels = { entry: 'Entrada', exit: 'Saída', adjustment: 'Ajuste' };
const money = (value: number) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const categoryName = (value: Product['categories']) => Array.isArray(value) ? value[0]?.name : value?.name;
const margin = (product: Product) => Number(product.sale_price) > 0 ? ((Number(product.sale_price) - Number(product.cost_price || 0)) / Number(product.sale_price)) * 100 : 0;

export function ProductsPage() {
  const toast = useToast();
  const [rows, setRows] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]);
  const [search, setSearch] = useState(''); const [categoryFilter, setCategoryFilter] = useState('Todas');
  const [name, setName] = useState(''); const [price, setPrice] = useState(''); const [cost, setCost] = useState(''); const [quantity, setQuantity] = useState(''); const [minimumStock, setMinimumStock] = useState(''); const [categoryId, setCategoryId] = useState('');
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Product | null>(null); const [menuId, setMenuId] = useState('');
  const [movementProduct, setMovementProduct] = useState<Product | null>(null); const [movementType, setMovementType] = useState<MovementType>('entry'); const [movementQuantity, setMovementQuantity] = useState(''); const [reason, setReason] = useState('');
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);

  async function load() { if (!supabase) return; const [productResult, categoryResult] = await Promise.all([supabase.from('products').select('id,name,brand,condition,sale_price,cost_price,quantity,minimum_stock,active,category_id,categories(name)').is('archived_at', null).order('created_at', { ascending: false }), supabase.from('categories').select('id,name').is('archived_at', null).order('name')]); setRows((productResult.data || []) as unknown as Product[]); setCategories((categoryResult.data || []) as Category[]); }
  useEffect(() => { load(); }, []);
  function startNew() { setEditing(null); setName(''); setPrice(''); setCost(''); setQuantity(''); setMinimumStock(''); setCategoryId(''); setError(''); setOpen(true); setMenuId(''); }
  function startEdit(product: Product) { setEditing(product); setName(product.name); setPrice(String(product.sale_price)); setCost(String(product.cost_price || '')); setQuantity(String(product.quantity)); setMinimumStock(String(product.minimum_stock)); setCategoryId(product.category_id || ''); setError(''); setOpen(true); setMenuId(''); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!supabase) { setError('Não foi possível conectar ao catálogo.'); return; } setSaving(true); setError(''); const payload = { name: name.trim(), sale_price: Number(price), cost_price: Number(cost || 0), quantity: Number(quantity), minimum_stock: Number(minimumStock || 0), category_id: categoryId || null }; const result = editing ? await supabase.from('products').update(payload).eq('id', editing.id).select('id,name,brand,condition,sale_price,cost_price,quantity,minimum_stock,active,category_id,categories(name)').single() : await supabase.from('products').insert(payload).select('id,name,brand,condition,sale_price,cost_price,quantity,minimum_stock,active,category_id,categories(name)').single(); if (result.error || !result.data) { setError('Não foi possível salvar o produto. Verifique os dados.'); setSaving(false); return; } setRows(prev => editing ? prev.map(row => row.id === editing.id ? result.data as unknown as Product : row) : [result.data as unknown as Product, ...prev]); setOpen(false); setEditing(null); toast.success(editing ? 'Produto atualizado com sucesso.' : 'Produto cadastrado com sucesso.'); setSaving(false); }
  async function deactivate(product: Product) { if (!supabase) return; setMenuId(''); if (product.active && !window.confirm(`Desativar o produto ${product.name}?`)) return; const nextActive = !product.active; const result = await supabase.from('products').update({ active: nextActive }).eq('id', product.id); if (result.error) { setError(`Não foi possível ${nextActive ? 'reativar' : 'desativar'} o produto.`); return; } setRows(prev => prev.map(row => row.id === product.id ? { ...row, active: nextActive } : row)); toast.success(nextActive ? 'Produto reativado.' : 'Produto desativado.'); }
  async function archive(product: Product) { if (!supabase || !window.confirm(`Excluir ${product.name}?`)) return; setMenuId(''); const result = await supabase.from('products').update({ archived_at: new Date().toISOString() }).eq('id', product.id); if (result.error) { setError('Não foi possível excluir o produto.'); return; } setRows(prev => prev.filter(row => row.id !== product.id)); toast.success('Produto excluído.'); }
  function openMovement(product: Product) { setMovementProduct(product); setMovementType('entry'); setMovementQuantity(''); setReason(''); setError(''); setMenuId(''); }
  async function saveMovement(event: FormEvent) { event.preventDefault(); if (!supabase || !movementProduct) return; const amount = Number(movementQuantity); if (!amount || amount <= 0 || !reason.trim()) { setError('Informe uma quantidade válida e o motivo da movimentação.'); return; } if (movementType === 'exit' && amount > movementProduct.quantity) { setError('A saída não pode ser maior que o estoque atual.'); return; } setSaving(true); setError(''); const nextQuantity = movementType === 'entry' ? movementProduct.quantity + amount : movementType === 'exit' ? movementProduct.quantity - amount : amount; const movement = await supabase.from('stock_movements').insert({ product_id: movementProduct.id, movement_type: movementType, quantity: amount, reason: reason.trim() }); const product = movement.error ? movement : await supabase.from('products').update({ quantity: nextQuantity }).eq('id', movementProduct.id).select('id,name,brand,condition,sale_price,cost_price,quantity,minimum_stock,active,category_id,categories(name)').single(); if (movement.error || product.error || !product.data) { setError('Não foi possível registrar a movimentação.'); setSaving(false); return; } setRows(prev => prev.map(row => row.id === movementProduct.id ? product.data as unknown as Product : row)); setMovementProduct(null); toast.success(`${movementLabels[movementType]} registrada com sucesso.`); setSaving(false); }
  const status = (product: Product) => !product.active ? ['red', 'Inativo'] : product.quantity === 0 ? ['red', 'Sem estoque'] : product.quantity <= product.minimum_stock ? ['gold', 'Estoque baixo'] : ['green', 'Ativo'];

  const visibleRows = useMemo(() => { const normalized = search.trim().toLocaleLowerCase(); return rows.filter(row => (!normalized || row.name.toLocaleLowerCase().includes(normalized) || (row.brand || '').toLocaleLowerCase().includes(normalized)) && (categoryFilter === 'Todas' || categoryName(row.categories) === categoryFilter)); }, [rows, search, categoryFilter]);
  const { page, setPage, pageCount, pageItems } = usePagination(visibleRows, 20);

  return <section className="content">
    <div className="page-toolbar-top"><span className="page-toolbar-count">{`${visibleRows.length} ${visibleRows.length === 1 ? 'produto' : 'produtos'}`}</span><button className="btn primary" onClick={startNew}><span aria-hidden="true">+</span> Produto</button></div>
    {error && !open && !movementProduct && <div className="error" role="alert">{error}</div>}
    {!open && !movementProduct && <div className="list-tools"><label className="list-search"><span className="sr-only">Buscar produtos</span><input className="input" placeholder="Buscar por nome ou marca" value={search} onChange={e => setSearch(e.target.value)} /></label><label className="sort-control">Categoria <select className="select" value={categoryFilter} onChange={e => setCategoryFilter(e.target.value)}><option>Todas</option>{categories.map(category => <option key={category.id}>{category.name}</option>)}</select></label></div>}
    {open && <form className="form-card" onSubmit={submit}><h3>{editing ? 'Editar produto' : 'Novo produto'}</h3><div className="form-grid"><div className="field"><label htmlFor="product-name">Nome <span className="required">*</span></label><input id="product-name" className="input" value={name} onChange={e => setName(e.target.value)} required /></div><div className="field"><label htmlFor="product-category">Categoria</label><select id="product-category" className="select" value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">Sem categoria</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div><div className="field"><label htmlFor="product-price">Preço de venda <span className="required">*</span></label><input id="product-price" className="input" type="number" min="0" step="0.01" value={price} onChange={e => setPrice(e.target.value)} required /></div><div className="field"><label htmlFor="product-cost">Preço de custo</label><input id="product-cost" className="input" type="number" min="0" step="0.01" value={cost} onChange={e => setCost(e.target.value)} /></div><div className="field"><label htmlFor="product-quantity">Quantidade <span className="required">*</span></label><input id="product-quantity" className="input" type="number" min="0" value={quantity} onChange={e => setQuantity(e.target.value)} required /></div><div className="field"><label htmlFor="product-minimum">Estoque mínimo</label><input id="product-minimum" className="input" type="number" min="0" value={minimumStock} onChange={e => setMinimumStock(e.target.value)} /></div></div>{error && <div className="error" role="alert">{error}</div>}<div className="actions"><button type="button" className="btn" onClick={() => setOpen(false)}>Cancelar</button><button className="btn primary" disabled={saving}>{saving ? 'Salvando…' : 'Salvar produto'}</button></div></form>}
    {movementProduct && <form className="form-card" onSubmit={saveMovement}><h3>Ajustar estoque · {movementProduct.name}</h3><div className="form-grid"><div className="field"><label htmlFor="movement-type">Tipo <span className="required">*</span></label><select id="movement-type" className="select" value={movementType} onChange={e => setMovementType(e.target.value as MovementType)}><option value="entry">Entrada</option><option value="exit">Saída</option><option value="adjustment">Ajuste</option></select></div><div className="field"><label htmlFor="movement-quantity">Quantidade <span className="required">*</span></label><input id="movement-quantity" className="input" type="number" min="1" value={movementQuantity} onChange={e => setMovementQuantity(e.target.value)} required /></div><div className="field full"><label htmlFor="movement-reason">Motivo <span className="required">*</span></label><input id="movement-reason" className="input" value={reason} onChange={e => setReason(e.target.value)} placeholder="Ex.: compra do fornecedor" required /></div></div><p className="muted">Estoque atual: {movementProduct.quantity} unidades.</p>{error && <div className="error" role="alert">{error}</div>}<div className="actions"><button type="button" className="btn" onClick={() => setMovementProduct(null)}>Cancelar</button><button className="btn primary" disabled={saving}>{saving ? 'Salvando…' : 'Registrar movimentação'}</button></div></form>}
    {rows.length === 0 && !open ? <section className="panel"><EmptyState icon="box" title="Nenhum produto cadastrado" description="Cadastre peças, acessórios e serviços para controlar preços e estoque." actionLabel="Cadastrar primeiro produto" actionTo="/admin/produtos" example="Depois você verá quantidade disponível, estoque mínimo e alertas." /></section> : <><div className="table-wrap"><table className="table"><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th>Margem</th><th>Quantidade</th><th>Status</th><th>Ações</th></tr></thead><tbody>{pageItems.map(row => { const [tone, label] = status(row); const productMargin = margin(row); return <tr key={row.id}><td><strong>{row.name}</strong><br /><span className="muted">{row.brand || 'Sem marca'}</span></td><td>{categoryName(row.categories) || <span className="muted">—</span>}</td><td>{money(row.sale_price)}</td><td><span className={`margin-value${productMargin < 20 ? ' is-low' : ''}`}>{productMargin.toFixed(0)}%</span></td><td>{row.quantity}</td><td><span className={`badge ${tone}`}>{label}</span></td><td className="action-cell"><button className="icon-button" aria-label={`Ações para ${row.name}`} aria-expanded={menuId === row.id} onClick={() => setMenuId(menuId === row.id ? '' : row.id)}>•••</button>{menuId === row.id && <div className="row-menu" role="menu"><button onClick={() => startEdit(row)}>Editar produto</button><button onClick={() => openMovement(row)}>Ajustar estoque</button><button onClick={() => deactivate(row)} disabled={!row.active}>Desativar produto</button><button className="danger" onClick={() => archive(row)}>Excluir produto</button></div>}</td></tr>; })}</tbody></table></div><Pagination page={page} pageCount={pageCount} onChange={setPage} totalLabel={`${visibleRows.length} ${visibleRows.length === 1 ? 'produto' : 'produtos'}`} /></>}
  </section>;
}
