import { EmptyState } from '../components/ui/EmptyState';

type Props = { eyebrow: string; title: string; description: string; items: string[] };
const copy: Record<string, { icon: Parameters<typeof import('../components/ui/Icon').Icon>[0]['name']; title: string; description: string; action: string; to: string; example: string }> = {
  Agenda: { icon: 'calendar', title: 'Nenhum compromisso agendado', description: 'Organize retiradas, retornos e horários combinados com seus clientes.', action: 'Agendar compromisso', to: '/admin/agenda', example: 'Aqui aparecerão os próximos horários, entregas previstas e confirmações.' },
  Estoque: { icon: 'box', title: 'Seu estoque está pronto para começar', description: 'Registre entradas, saídas e ajustes para saber exatamente o que está disponível.', action: 'Registrar entrada', to: '/admin/produtos', example: 'Depois você verá níveis atuais, estoque mínimo e alertas críticos.' },
  Vendas: { icon: 'cart', title: 'Nenhuma venda registrada', description: 'Venda produtos e serviços, associe o cliente e acompanhe os pagamentos.', action: 'Registrar primeira venda', to: '/admin/vendas', example: 'Aqui aparecerão vendas recentes, ticket médio e formas de pagamento.' },
  Financeiro: { icon: 'wallet', title: 'Seu fluxo financeiro está vazio', description: 'Registre entradas e saídas para acompanhar o saldo e a saúde da loja.', action: 'Adicionar movimentação', to: '/admin/financeiro', example: 'Você verá saldo, categorias, contas a pagar e a receber.' },
  Relatórios: { icon: 'chart', title: 'Ainda não há dados para analisar', description: 'Conclua atendimentos e vendas para gerar indicadores da operação.', action: 'Ver comandas', to: '/admin/comandas', example: 'Faturamento, margem, ticket médio e tempo de reparo aparecerão aqui.' },
  Usuários: { icon: 'users', title: 'Convide sua equipe', description: 'Adicione usuários e defina permissões para cada função da assistência.', action: 'Adicionar usuário', to: '/admin/usuarios', example: 'Depois você verá perfis, acessos e o registro de atividades.' },
  Configurações: { icon: 'settings', title: 'Configure sua loja', description: 'Personalize dados, mensagens e preferências para deixar a operação com a sua cara.', action: 'Editar dados da loja', to: '/admin/configuracoes', example: 'Dados da loja, WhatsApp e privacidade ficam organizados aqui.' },
};
export function ModulePage({ eyebrow, title, description, items }: Props) { const state = copy[title]; return <section className="content"><div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2><p>{description}</p></div></div><div className="module-overview">{items.map((item, index)=><article className="card module-stat" key={item}><span>{item}</span><strong>{index === 0 ? '—' : '0'}</strong><small>Aguardando dados</small></article>)}</div><section className="panel module-empty-panel"><EmptyState icon={state.icon} title={state.title} description={state.description} actionLabel={state.action} actionTo={state.to} example={state.example}/></section></section>; }
